# Generated by Django 2.1.5 on 2019-11-08 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_conatct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Conatct',
            new_name='Contact',
        ),
    ]
